<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title><?php echo $currentTitle ?></title>
		<link rel="stylesheet" type="text/css" href="semantic/out/semantic.min.css">
		<script
		  src="https://code.jquery.com/jquery-3.1.1.min.js"
		  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
		  crossorigin="anonymous"></script>
		<script src="semantic/out/semantic.min.js"></script>
		<link rel="stylesheet" type="text/css" href="overrides/background.css">
		<meta name = "viewport" content = "width=device-width, initial-scale=1.0">
        
	</head>